//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet_Shop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class DichVu
    {
        [DisplayName("Tên Dịch vụ")]
        public string MaDV { get; set; }
        public string TenDV { get; set; }
    
        public virtual DoiTuongKD DoiTuongKD { get; set; }
    }
}
