//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet_Shop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DoDungTC
    {
        [Display(Name = "Mã đồ dùng")]
        public string MaDD { get; set; }
        [Display(Name = "Tên đồ dùng")]
        public string TenDD { get; set; }
        [Display(Name = "Mã loại thú cưng")]
        public string MaLoaiTC { get; set; }
        [Display(Name = "Mã nhà sản xuất")]
        public string MaNSX { get; set; }
        [Display(Name = "Mã loại đồ dùng")]
        public string MaLoaiDD { get; set; }
        [Display(Name = "Số lượng")]
        public Nullable<int> SoLuong { get; set; }
        [Display(Name = "Hãng sản xuất")]
        public virtual HangSX HangSX { get; set; }
        [Display(Name = "Loại đồ dùng")]
        public virtual LoaiDD LoaiDD { get; set; }
        [Display(Name = "Loại thú cưng")]
        public virtual LoaiThuCung LoaiThuCung { get; set; }
        [Display(Name = "Đối tượng")]
        public virtual DoiTuongKD DoiTuongKD { get; set; }
    }
}
