//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet_Shop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class DoDungTC
    {
        public string MaDD { get; set; }
        [DisplayName("Tên đồ dùng")]
        public string TenDD { get; set; }
        [DisplayName("Loài")]
        public string MaLoaiTC { get; set; }
        public string MaNSX { get; set; }
        [DisplayName("Hãng sản xuất")]
        public virtual HangSX HangSX { get; set; }
        [DisplayName("Loại Thú Cưng")]
        public virtual LoaiThuCung LoaiThuCung { get; set; }
        public virtual DoiTuongKD DoiTuongKD { get; set; }
    }
}
