//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet_Shop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.CT_HoaDon = new HashSet<CT_HoaDon>();
        }
        [DisplayName("Mã hóa đơn")]
        public string SoHD { get; set; }
        [DisplayName("Ngày lập")]
        public string NgayLap { get; set; }
        [DisplayName("Tổng thành tiền")]
        public Nullable<decimal> TongThanhTien { get; set; }
        [DisplayName("Mã nhân sự")]
        public string MaNS { get; set; }
        [DisplayName("Tên khách hàng")]
        public string TenKH { get; set; }
        [DisplayName("Địa chỉ")]
        public string DiaChi { get; set; }
        [DisplayName("Mã người dùng")]
        public string IdNguoiDung { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_HoaDon> CT_HoaDon { get; set; }
        public virtual NhanSU NhanSU { get; set; }
    }
}
