//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet_Shop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class PhieuDat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuDat()
        {
            this.CT_PhieuDat = new HashSet<CT_PhieuDat>();
        }
        [DisplayName("Số phiếu đặt")]
        public string SoPD { get; set; }
        [DisplayName("Ngày lập")]
        public Nullable<System.DateTime> NgayLap { get; set; }
        [DisplayName("Số tiền cọc")]
        public Nullable<decimal> SoTienCoc { get; set; }
        [DisplayName("Hình thức cọc")]
        public string HinhThucCoc { get; set; }
        [DisplayName("Ngày hẹn")]
        public string NgayHen { get; set; }
        [DisplayName("Mã người dùng")]
        public string IdNguoiDung { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PhieuDat> CT_PhieuDat { get; set; }
    }
}
