//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet_Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThuCung
    {
        public string MaTC { get; set; }
        public string TenTC { get; set; }
        public string MaLoaiTC { get; set; }
        public Nullable<int> GioiTinh { get; set; }
        public string KichCo { get; set; }
        public Nullable<int> TiemPhong { get; set; }
    
        public virtual DoiTuongKD DoiTuongKD { get; set; }
        public virtual LoaiThuCung LoaiThuCung { get; set; }
    }
}
